using System.Collections.Generic;
using UnityEngine;

public class Player_Controller : MonoBehaviour
{
     // Movement speed of player character
    public float speed = 5.0f;
    // facing Direction = player scale X value. 1 = facingRight
    public int facingDirection = 1;
    public Rigidbody2D playerRB;
    public Animator playerAnimator;


    public Node currentNode;
    public List<Node> path = new List<Node>();


    // Update is called once per frame
    void Update()
    {
        // key input: a/< left: -1; d/> right: 1; no input: 0;
        float horizontalInput = Input.GetAxis("Horizontal");
        // key input: s/< down: -1; w/> up 1; no input: 0;
        float verticalInput = Input.GetAxis("Vertical");

        // Check if horizontal Input switches from left to right
        // Check input and see if it doesn't match current localScale.x (facingDirection)
        if (horizontalInput > 0 && transform.localScale.x < 0 ||
        horizontalInput < 0 && transform.localScale.x > 0)
        {
            FlipPlayer();
        }

        // Set input values to self definded variables "horizontal" and "vertical" in animator
        // Animator animates if input 0<. Input can sometimes be >0.
        // Mathf.Abs() turn number into absolute (positive) numbers.
        // Logic now: If input =! 0 -> animate
        playerAnimator.SetFloat("horizontal", Mathf.Abs(horizontalInput));
        playerAnimator.SetFloat("vertical", Mathf.Abs(verticalInput));

        // Move player
        playerRB.linearVelocity = new Vector2(horizontalInput, verticalInput) * speed;



        //CreatePath();
    }

    void FlipPlayer()
    {
        // Switch facingDirection positive <---> negative
        facingDirection *= -1;
        // Set localScale.x to facingDirection. Keep .y and .z
        transform.localScale = new Vector3(transform.localScale.x * -1, transform.localScale.y, transform.localScale.z);
    }

    // moves the player along the path generated by the A* algorithm, and generates a new path when the current path is empty
    public void CreatePath()
    {
        if (path.Count > 0)
        {
            // move towards the next node in the path, and if we are close enough to it, remove it from the path and set it as the current node
            int x = 0;
            transform.position = Vector3.MoveTowards(transform.position, new Vector3(path[x].transform.position.x, path[x].transform.position.y, -2), 5 * Time.deltaTime);

            if (Vector2.Distance(transform.position, path[x].transform.position) < 0.1f)
            {
                currentNode = path[x];
                path.RemoveAt(x);
            }
        }
        else
        {
            // if the path is empty, generate a new path to a random node in the scene
            Node[] nodes = FindObjectsByType<Node>(FindObjectsSortMode.None);
            while(path == null || path.Count == 0)
            {
                path = AStarManager.instance.generatePath(currentNode, nodes[Random.Range(0, nodes.Length)]);
            }
        }
    }

    private void OnDrawGizmos()
    {
        if (path.Count > 0)
        {
            Gizmos.color = Color.blue;
            for (int i = 1; i < path.Count; i++)
            {
                Gizmos.DrawLine(path[i].transform.position, path[i - 1].transform.position);
            }
        }
    }
}
